using Arahk.Neighbor.Domain.Constants;

namespace Arahk.Neighbor.Web.Services;

/// <summary>Thai UI strings locked from UX 03-copy-th.md.</summary>
public static class ThaiCopy
{
    private static readonly Dictionary<string, string> Map = new()
    {
        ["app.wordmark"] = "Neighbor",
        ["app.tagline"] = "เพื่อนบ้าน",
        [ErrorKeys.NetworkGeneric] = "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
        [ErrorKeys.ServerGeneric] = "ระบบขัดข้องชั่วคราว กรุณาลองใหม่ภายหลัง",
        ["action.retry"] = "ลองใหม่",

        ["login.title"] = "เข้าสู่ระบบ",
        ["login.mode.email"] = "อีเมล",
        ["login.mode.phone"] = "เบอร์โทร",
        ["login.cta"] = "เข้าสู่ระบบ",
        ["login.link.register"] = "ยังไม่มีบัญชี? สมัครสมาชิก",
        ["login.link.forgot"] = "ลืมรหัสผ่าน?",
        ["login.forgot.soon"] = "ฟีเจอร์นี้จะเปิดให้ใช้เร็วๆ นี้",
        ["login.email.label"] = "อีเมล",
        ["login.email.placeholder"] = "you@email.com",
        ["login.phone.label"] = "เบอร์โทรศัพท์",
        ["login.phone.placeholder"] = "08X XXX XXXX",
        ["login.phone.helper"] = "ใช้เบอร์ที่ผูกกับบัญชีแล้ว",
        ["login.password.label"] = "รหัสผ่าน",
        ["login.password.placeholder"] = "รหัสผ่านของคุณ",

        [ErrorKeys.EmailRequired] = "กรุณากรอกอีเมล",
        [ErrorKeys.EmailFormat] = "รูปแบบอีเมลไม่ถูกต้อง",
        [ErrorKeys.PhoneRequired] = "กรุณากรอกเบอร์โทรศัพท์",
        [ErrorKeys.PhoneFormat] = "รูปแบบเบอร์โทรไม่ถูกต้อง",
        [ErrorKeys.PasswordRequired] = "กรุณากรอกรหัสผ่าน",
        [ErrorKeys.LoginCredentials] = "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
        [ErrorKeys.LoginCredentialsPhone] = "เบอร์โทรหรือรหัสผ่านไม่ถูกต้อง",
        [ErrorKeys.LoginPhoneNotLinked] = "ไม่พบบัญชีที่ผูกกับเบอร์นี้",

        ["register.title"] = "สมัครสมาชิก",
        ["register.cta"] = "สมัครสมาชิก",
        ["register.link.login"] = "มีบัญชีแล้ว? เข้าสู่ระบบ",
        ["register.terms.prefix"] = "ฉันยอมรับ",
        ["register.terms.tos"] = "ข้อกำหนดการใช้บริการ",
        ["register.terms.and"] = "และ",
        ["register.terms.privacy"] = "นโยบายความเป็นส่วนตัว",
        ["register.success.otp_sent"] = "สมัครสำเร็จ เราส่งรหัส OTP ไปที่อีเมลของคุณแล้ว",
        ["register.displayname.label"] = "ชื่อที่แสดง",
        ["register.displayname.placeholder"] = "เช่น คุณมานี",
        ["register.displayname.helper"] = "เพื่อนบ้านจะเห็นชื่อนี้",
        ["register.email.label"] = "อีเมล",
        ["register.email.placeholder"] = "you@email.com",
        ["register.email.helper"] = "เราจะส่งรหัสยืนยันไปที่อีเมลนี้",
        ["register.phone.label"] = "เบอร์โทรศัพท์ (ไม่บังคับ)",
        ["register.phone.placeholder"] = "08X XXX XXXX",
        ["register.phone.helper"] = "เพิ่มทีหลังได้ · ใช้เข้าสู่ระบบด้วยเบอร์ได้เมื่อผูกแล้ว",
        ["register.password.label"] = "รหัสผ่าน",
        ["register.password.placeholder"] = "อย่างน้อย 8 ตัวอักษร",
        ["register.password.helper"] = "ต้องมีทั้งตัวอักษรและตัวเลข",
        ["register.password_confirm.label"] = "ยืนยันรหัสผ่าน",
        ["register.password_confirm.placeholder"] = "กรอกรหัสผ่านอีกครั้ง",

        [ErrorKeys.DisplayNameRequired] = "กรุณากรอกชื่อที่แสดง",
        [ErrorKeys.DisplayNameMin] = "ชื่อสั้นเกินไป (อย่างน้อย 2 ตัวอักษร)",
        [ErrorKeys.DisplayNameMax] = "ชื่อยาวเกินไป (ไม่เกิน 50 ตัวอักษร)",
        [ErrorKeys.EmailDuplicate] = "อีเมลนี้ถูกใช้แล้ว",
        [ErrorKeys.PasswordMin] = "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
        [ErrorKeys.PasswordComplexity] = "รหัสผ่านต้องมีทั้งตัวอักษรและตัวเลข",
        [ErrorKeys.PasswordConfirmRequired] = "กรุณายืนยันรหัสผ่าน",
        [ErrorKeys.PasswordConfirmMismatch] = "รหัสผ่านไม่ตรงกัน",
        [ErrorKeys.TermsRequired] = "กรุณายอมรับข้อกำหนดเพื่อสมัครสมาชิก",

        ["otp.title"] = "ยืนยันอีเมล",
        ["otp.subtitle"] = "กรอกรหัส 6 หลักที่ส่งไปยัง",
        ["otp.field_label"] = "รหัส OTP",
        ["otp.placeholder"] = "000000",
        ["otp.helper_expiry"] = "รหัสมีอายุ 10 นาที",
        ["otp.cta"] = "ยืนยัน",
        ["otp.resend"] = "ส่งรหัสอีกครั้ง",
        ["otp.resend_in"] = "ส่งอีกครั้งใน {seconds} วินาที",
        ["otp.back"] = "กลับไปแก้ไขข้อมูลสมัคร",
        ["otp.toast.sent"] = "ส่งรหัส OTP แล้ว",
        ["otp.toast.resent"] = "ส่งรหัส OTP ใหม่แล้ว",
        ["otp.success"] = "ยืนยันอีเมลสำเร็จ",

        [ErrorKeys.OtpRequired] = "กรุณากรอกรหัส 6 หลัก",
        [ErrorKeys.OtpFormat] = "รหัส OTP ต้องเป็นตัวเลข 6 หลัก",
        [ErrorKeys.OtpInvalid] = "รหัสไม่ถูกต้อง กรุณาลองใหม่",
        [ErrorKeys.OtpInvalidRemaining] = "รหัสไม่ถูกต้อง (เหลือ {n} ครั้ง)",
        [ErrorKeys.OtpExpired] = "รหัสหมดอายุแล้ว กรุณาขอรหัสใหม่",
        [ErrorKeys.OtpMaxAttempts] = "คุณกรอกรหัสผิดเกินกำหนด กรุณาขอรหัสใหม่",
        [ErrorKeys.OtpCooldown] = "กรุณารอสักครู่ก่อนขอรหัสใหม่",

        ["state.loading"] = "กำลังโหลด...",
        ["state.submitting"] = "กำลังดำเนินการ...",
        ["state.sending_otp"] = "กำลังส่งรหัส...",
        ["home.welcome"] = "ยินดีต้อนรับ",
        ["home.signed_in_as"] = "เข้าสู่ระบบแล้วในชื่อ",
        ["home.logout"] = "ออกจากระบบ",
        ["dev.otp_hint"] = "รหัส OTP (โหมดพัฒนา)",

        // Layout / App shell (Home UX 03-copy-th.md)
        ["layout.nav.menu_toggle_aria"] = "เปิดหรือปิดเมนู",
        ["layout.sign_out"] = "ออกจากระบบ",
        ["layout.drawer.close_aria"] = "ปิดเมนูนำทาง",
        ["a11y.main_nav"] = "เมนูหลัก",
        ["a11y.current_page"] = "หน้าปัจจุบัน",

        ["nav.home"] = "หน้าหลัก",
        ["nav.payment"] = "การชำระเงิน",
        ["nav.packages"] = "แพ็กเกจ",
        ["nav.visitor"] = "ผู้มาเยือน",
        ["nav.master_data"] = "ข้อมูลหลัก",

        ["home.welcome.headline"] = "ยินดีต้อนรับกลับบ้าน",
        ["home.welcome.body"] = "Neighbor ช่วยรวบรวมและจัดการข้อมูลของหมู่บ้าน เพื่อรองรับความต้องการของลูกบ้านและนิติบุคคลผู้บริหารดูแล — จุดเด่นคือข้อมูลเป็นของลูกบ้านและหมู่บ้าน แม้เปลี่ยนบริษัทนิติบุคคลที่ดูแล ข้อมูลก็ยังอยู่กับหมู่บ้านเช่นเดิม",
        ["home.welcome.tip"] = "ใช้เมนูด้านข้างเพื่อไปยังบริการต่างๆ ของหมู่บ้าน",
        ["home.welcome.tip_mobile"] = "แตะไอคอนเมนูด้านบนเพื่อเปิดรายการบริการ",
        ["home.welcome.illustration_alt"] = "ภาพประกอบบ้านและครอบครัวอบอุ่น",

        ["soon.title"] = "เร็วๆ นี้",
        ["soon.body_generic"] = "ส่วนนี้ยังไม่พร้อมใช้งาน ขอขอบคุณที่แวะมา",
        ["soon.body_named"] = "เมนู「{navLabel}」ยังไม่พร้อมใช้งานในตอนนี้",
        ["soon.body_reassure"] = "คุณยังดูหน้าหลักได้ตามสบาย — เราจะแจ้งเมื่อพร้อม",
        ["soon.cta_home"] = "ไปหน้าหลัก",

        // Master Data shell
        ["master.page.title"] = "ข้อมูลหลัก",
        ["master.page.subtitle"] = "ตั้งค่าข้อมูลพื้นฐานของชุมชน",
        ["master.select.label"] = "ส่วนข้อมูลหลัก",
        ["master.select.aria"] = "เลือกส่วนข้อมูลหลัก",
        ["master.tab.houses"] = "บ้าน",
        ["master.tab.calendar"] = "ปฏิทิน",
        ["master.tab.activities"] = "กิจกรรม",
        ["master.tab.announcements"] = "ข่าวประกาศ",
        ["master.tab.users"] = "ผู้ใช้",
        ["master.tab.roles"] = "บทบาทผู้ใช้",
        ["master.tab.permissions"] = "สิทธิ์",
        ["master.a11y.tab_inactive"] = "ยังไม่พร้อมใช้งาน",

        // Houses
        ["houses.page.title"] = "บ้านในชุมชน",
        ["houses.page.subtitle"] = "จัดการเลขที่บ้านและซอยของชุมชน",
        ["houses.count"] = "ทั้งหมด {n} หลัง",
        ["houses.count_one"] = "ทั้งหมด 1 หลัง",
        ["houses.action.add"] = "เพิ่มบ้าน",
        ["houses.action.import"] = "นำเข้า Excel",
        ["houses.action.save"] = "บันทึก",
        ["houses.action.cancel"] = "ยกเลิก",
        ["houses.action.edit"] = "แก้ไข",
        ["houses.action.delete"] = "ลบ",
        ["houses.action.choose_file"] = "เลือกไฟล์",
        ["houses.action.collapse_import"] = "ย่อ",
        ["houses.action.expand_import"] = "นำเข้า Excel",
        ["houses.action.dismiss_result"] = "ปิดข้อความ",
        ["houses.table.house_no"] = "บ้านเลขที่",
        ["houses.table.soi"] = "ซอย",
        ["houses.table.actions"] = "จัดการ",
        ["houses.table.soi_empty"] = "—",
        ["houses.table.edit_aria"] = "แก้ไขบ้านเลขที่ {houseNo}",
        ["houses.table.delete_aria"] = "ลบบ้านเลขที่ {houseNo}",
        ["houses.table.loading"] = "กำลังโหลดรายการบ้าน…",
        ["houses.empty.title"] = "ยังไม่มีบ้านในชุมชน",
        ["houses.empty.body"] = "เริ่มเพิ่มทีละหลัง หรือนำเข้าจากไฟล์ Excel ตามรูปแบบที่กำหนด",
        ["houses.empty.hint"] = "บ้านเลขที่ต้องไม่ซ้ำกันในชุมชน",
        ["houses.add.title"] = "เพิ่มบ้าน",
        ["houses.add.subtitle"] = "กรอกเลขที่บ้านในชุมชนของคุณ",
        ["houses.add.field.house_no"] = "บ้านเลขที่",
        ["houses.add.field.soi_optional"] = "ซอย (ไม่บังคับ)",
        ["houses.add.placeholder.house_no"] = "เช่น 12/1",
        ["houses.add.placeholder.soi"] = "เช่น ซอยร่มเงา",
        ["houses.add.helper.house_no"] = "ต้องไม่ซ้ำกับบ้านอื่นในชุมชน",
        ["houses.error.house_no_required"] = "กรุณากรอกบ้านเลขที่",
        ["houses.error.house_no_duplicate"] = "บ้านเลขที่นี้มีอยู่แล้วในชุมชน",
        ["houses.error.house_no_too_long"] = "บ้านเลขที่ยาวเกินไป (สูงสุด {max} ตัวอักษร)",
        ["houses.error.soi_too_long"] = "ซอยยาวเกินไป (สูงสุด {max} ตัวอักษร)",
        ["houses.error.network"] = "ไม่สามารถบันทึกได้ในขณะนี้ กรุณาลองอีกครั้ง",
        ["houses.error.server"] = "เกิดข้อผิดพลาดจากระบบ กรุณาลองอีกครั้ง",
        ["houses.error.not_found"] = "ไม่พบบ้านที่ต้องการ",
        ["houses.success.added"] = "เพิ่มบ้านแล้ว",
        ["houses.success.added_detail"] = "บันทึกบ้านเลขที่ {houseNo} เรียบร้อย",
        ["houses.edit.title"] = "แก้ไขบ้าน",
        ["houses.edit.subtitle"] = "ปรับเลขที่บ้านหรือซอยในชุมชนของคุณ",
        ["houses.edit.field.house_no"] = "บ้านเลขที่",
        ["houses.edit.field.soi_optional"] = "ซอย (ไม่บังคับ)",
        ["houses.edit.helper.house_no"] = "ต้องไม่ซ้ำกับบ้านอื่นในชุมชน",
        ["houses.edit.placeholder.house_no"] = "เช่น 12/1",
        ["houses.edit.placeholder.soi"] = "เช่น ซอยร่มเงา",
        ["houses.success.updated"] = "บันทึกการแก้ไขแล้ว",
        ["houses.success.updated_detail"] = "อัปเดตบ้านเลขที่ {houseNo} เรียบร้อย",
        ["houses.delete.title"] = "ลบบ้าน?",
        ["houses.delete.body"] = "ต้องการลบบ้านเลขที่ 「{houseNo}」 ออกจากชุมชนหรือไม่?",
        ["houses.delete.warn"] = "การลบนี้ไม่สามารถย้อนกลับได้จากหน้านี้",
        ["houses.delete.confirm"] = "ลบ",
        ["houses.delete.cancel"] = "ยกเลิก",
        ["houses.success.deleted"] = "ลบบ้านแล้ว",
        ["houses.success.deleted_detail"] = "ลบบ้านเลขที่ {houseNo} เรียบร้อย",
        ["houses.error.delete_failed"] = "ไม่สามารถลบบ้านได้ในขณะนี้ กรุณาลองอีกครั้ง",
        ["houses.error.delete_conflict"] = "ไม่สามารถลบบ้านนี้ได้ เพราะอาจมีข้อมูลอื่นที่เชื่อมอยู่",
        ["houses.import.title"] = "นำเข้าจาก Excel",
        ["houses.import.upload.title"] = "ลากไฟล์มาวาง หรือเลือกไฟล์",
        ["houses.import.upload.hint"] = "รองรับไฟล์ .xlsx เท่านั้น · ชีตชื่อ Houses",
        ["houses.import.file_selected"] = "ไฟล์ที่เลือก: {fileName}",
        ["houses.import.working"] = "กำลังนำเข้า…",
        ["houses.import.guide.title"] = "วิธีสร้างไฟล์ Excel",
        ["houses.import.guide.example_caption"] = "ตัวอย่างตาราง (แถวแรกเป็นหัวคอลัมน์)",
        ["houses.import.guide.step1"] = "เปิด Microsoft Excel หรือ Google Sheets",
        ["houses.import.guide.step2"] = "เปลี่ยนชื่อชีต (แท็บด้านล่าง) เป็น **Houses** ให้ตรงทุกตัวอักษร",
        ["houses.import.guide.step3"] = "ที่แถวแรกใส่หัวคอลัมน์: คอลัมน์ A = **HouseNo** · คอลัมน์ B = **Soi**",
        ["houses.import.guide.step4"] = "ใส่ข้อมูลบ้านตั้งแต่แถวที่ 2 เป็นต้นไป",
        ["houses.import.guide.step5"] = "บันทึกไฟล์เป็นนามสกุล **.xlsx** แล้วกลับมาอัปโหลดที่นี่",
        ["houses.import.guide.note_sheet"] = "ชื่อชีตต้องเป็น Houses เท่านั้น",
        ["houses.import.guide.note_header"] = "แถวแรกต้องเป็นหัวคอลัมน์ HouseNo และ Soi",
        ["houses.import.guide.note_required"] = "ทุกแถวต้องมี HouseNo · Soi เว้นว่างได้",
        ["houses.import.guide.note_dup"] = "บ้านเลขที่ซ้ำกับที่มีอยู่หรือซ้ำในไฟล์จะถูกข้าม ไม่ทับของเดิม",
        ["houses.import.guide.example_note"] = "แถวที่ 2 ซอยว่างได้ — ระบบจะบันทึกเฉพาะบ้านเลขที่",
        ["houses.import.error.bad_type"] = "กรุณาเลือกไฟล์ .xlsx เท่านั้น",
        ["houses.import.error.empty_file"] = "ไฟล์ว่างหรือไม่มีข้อมูลให้นำเข้า",
        ["houses.import.error.no_sheet"] = "ไม่พบชีตชื่อ Houses — กรุณาตั้งชื่อชีตให้ตรง",
        ["houses.import.error.bad_headers"] = "หัวคอลัมน์ไม่ถูกต้อง แถวแรกต้องเป็น HouseNo และ Soi",
        ["houses.import.error.missing_columns"] = "ไฟล์ต้องมีคอลัมน์ HouseNo และ Soi",
        ["houses.import.error.too_large"] = "ไฟล์ใหญ่เกินไป (สูงสุด {maxMb} MB)",
        ["houses.import.error.too_many_rows"] = "จำนวนแถวเกินกำหนด (สูงสุด {max} แถวต่อครั้ง)",
        ["houses.import.error.generic"] = "ไม่สามารถอ่านไฟล์นี้ได้ กรุณาตรวจสอบรูปแบบแล้วลองใหม่",
        ["houses.import.error.network"] = "ไม่สามารถนำเข้าได้ในขณะนี้ กรุณาลองอีกครั้ง",
        ["houses.import.result.title_ok"] = "นำเข้าสำเร็จ",
        ["houses.import.result.title_partial"] = "นำเข้าเสร็จสิ้น",
        ["houses.import.result.title_fail"] = "ไม่สามารถนำเข้าไฟล์นี้",
        ["houses.import.result.full"] = "สำเร็จ {ok} แถว",
        ["houses.import.result.partial"] = "สำเร็จ {ok} แถว · ข้าม {skip} แถวเพราะซ้ำ · ไม่ผ่าน {fail} แถว",
        ["houses.import.result.partial_no_fail"] = "สำเร็จ {ok} แถว · ข้าม {skip} แถวเพราะซ้ำ",
        ["houses.import.result.none_imported"] = "ไม่มีแถวที่นำเข้าได้",
        ["houses.import.result.row_dup_existing"] = "แถว {row}: บ้านเลขที่ซ้ำกับที่มีอยู่",
        ["houses.import.result.row_dup_file"] = "แถว {row}: บ้านเลขที่ซ้ำในไฟล์",
        ["houses.import.result.row_missing_no"] = "แถว {row}: ไม่มีบ้านเลขที่",
        ["houses.import.result.row_too_long"] = "แถว {row}: บ้านเลขที่หรือซอยยาวเกินกำหนด",
        ["houses.a11y.page"] = "หน้าข้อมูลหลัก บ้านในชุมชน",
        ["houses.a11y.add_dialog"] = "กล่องโต้ตอบเพิ่มบ้าน",
        ["houses.a11y.import_region"] = "ส่วนนำเข้าไฟล์ Excel",
        ["houses.a11y.close_dialog"] = "ปิด",
        ["houses.a11y.required"] = "จำเป็น",
    };

    public static string T(string key) => Map.TryGetValue(key, out var v) ? v : key;

    public static string Format(string key, params (string name, object? value)[] args)
    {
        var text = T(key);
        foreach (var (name, value) in args)
            text = text.Replace("{" + name + "}", value?.ToString() ?? "", StringComparison.Ordinal);
        return text;
    }
}
